# Generated by Django 4.1.4 on 2022-12-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('boxno', models.IntegerField()),
                ('qtrack_email', models.EmailField(max_length=100)),
                ('qtrack_password', models.CharField(max_length=100)),
                ('sudo_password', models.CharField(max_length=100)),
            ],
        ),
    ]
